### ISSUE TITLE
json2timeseriesdb does not produce any output

### ISSUE THREAD

**Issue by tuxmea** [puppetlabs/puppetlabs-puppet_metrics_collector#193]
## Describe the Bug
The json2timeseriesdb script does not produce any output when passing a metrics collector json file.

## Expected Behavior
The script generates the proper influxdb compatible output

## Steps to Reproduce
/opt/puppetlabs/puppet-metrics-collector/scripts/json2timeseriesdb /opt/puppetlabs/puppet-metrics-collector/system_processes/*/*.json

## Environment
 - Version Puppet 7, PE 2021, PE 2023
 - Platform SLES12, SLES15, Ubuntu 20, EL7, EL8

## Additional Context
We want to make use of the script to push data into the puppet operational dashboard based influxdb

**Comment by m0dular** [comment]
We deprecated remote shipping in the latest version where this file is removed https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector/blob/39dd7b2e1cb9fbc9cc39f4b870b53f48f7b66834/manifests/init.pp#L219-L224.  

It is possible to load system metrics or any other type using the [load_metrics plan](https://github.com/puppetlabs/puppet_operational_dashboards/blob/1291e7e40a66f882961f5875e06fabbff0c76f6f/plans/load_metrics.pp#L11-L12), but because it uses the Puppet HTTP client it's unable to access the Puppet certs and can't use SSL.  You could point the `metrics_dir` to where the collector outputs the files if you disable SSL for InfluxDB.  I'm sure it's possible to take the Starlark scripts [here](https://github.com/puppetlabs/puppet_operational_dashboards/tree/main/files/plan_files) and create a configuration for Telegraf to ship them to an SSL-enabled InfluxDB, but we don't currently have plans for that.
