### ISSUE TITLE
(SUP-2735) Push Metrics into SSL interface

### ISSUE THREAD

**Issue by tuxmea** [puppetlabs/puppetlabs-puppet_metrics_collector#72]
## Use Case
All communication must be encrypted using e.g. SSL.
The cron job to push metrics to influx only has tcp and http options, but no support for https.

## Describe the Solution You Would Like
Cron job which pushes metrics to https influxdb.

## Describe Alternatives You've Considered
Using puppet metrics dashboard and telegraf on SLES is nor supported.
We mus use the metrics collector.
We are not allowed to establish an ssl tunnel between the systems.

**Comment by jarretlavallee** [comment]
@tuxmea To use HTTPS, would you expect it to use the Puppet certificates or ones that you provide?

**Comment by tuxmea** [comment]
@jarretlavallee It should be possible to specify either a Puppet CA SSL certificate or any other cert coming from a PKI.

**Comment by m0dular** [comment]
Hi @tuxmea, I believe you installed [puppet_operational_dashboards](https://github.com/puppetlabs/puppet_operational_dashboards) and that resolved this issue?  We do support SLES and default to using SSL in that module.  I'll go ahead and close this issue since `puppet_metrics_dashboards` is deprecated in favor of `puppet_operational_dashboards` and the latter solves this issue.
